In [44]:
import pandas as pd
import numpy as np
import gzip
import json

In [45]:
steam = pd.read_csv('./Data\Data-Limpia\steam_games_limpio.csv')

In [46]:
steam

,app_name,genres,año,id
0,Lost summoner kitty,"['Strategy', 'Action', 'Indie', 'Casual', 'Sim...",2018,761140.0
1,Ironbound,"['Free to Play', 'Strategy', 'Indie', 'RPG', '...",2018,643980.0
2,Real pool 3d - poolians,"['Free to Play', 'Simulation', 'Sports', 'Casu...",2017,670290.0
3,弹炸人2222,"['Action', 'Adventure', 'Casual']",2017,767400.0
4,Log challenge,"['Action', 'Indie', 'Casual', 'Sports']",2016,773570.0
...,...,...,...,...
31326,Colony on mars,"['Strategy', 'Indie', 'Casual', 'Simulation']",2018,773640.0
31327,Logistical: south africa,"['Strategy', 'Indie', 'Casual']",2018,733530.0
31328,Russian roads,"['Indie', 'Simulation', 'Racing']",2018,610660.0
31329,Exit 2 - directions,"['Indie', 'Casual', 'Puzzle', 'Singleplayer', ...",2017,658870.0
31330,Maze run vr,"['Early Access', 'Adventure', 'Indie', 'Action...",2016,681550.0

In [47]:
items = pd.read_csv('./Data/Data-Limpia/user_items_limpio.csv')

In [48]:
items

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10.0,Counter-strike,0.100000
1,76561197970982479,20.0,Team fortress classic,0.000000
2,76561197970982479,30.0,Day of defeat,0.116667
3,76561197970982479,40.0,Deathmatch classic,0.000000
4,76561197970982479,50.0,Half-life: opposing force,0.000000
...,...,...,...,...
5094077,76561198329548331,346330.0,Brainbread 2,0.000000
5094078,76561198329548331,373330.0,All is dust,0.000000
5094079,76561198329548331,388490.0,One way to die: steam edition,0.050000
5094080,76561198329548331,521570.0,You have 10 seconds 2,0.066667
5094081,76561198329548331,519140.0,Minds eyes,0.050000

In [49]:
Funciones1 = pd.merge(items, steam, left_on='item_name', right_on='app_name', how='inner')

In [50]:
Funciones1 ###hacer merge con id y item id

,user_id,item_id,item_name,playtime_forever,app_name,genres,año,id
0,76561197970982479,10.0,Counter-strike,0.100000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
1,js41637,10.0,Counter-strike,0.000000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
2,Riot-Punch,10.0,Counter-strike,0.000000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
3,doctr,10.0,Counter-strike,1.550000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
4,corrupted_soul,10.0,Counter-strike,1.800000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
...,...,...,...,...,...,...,...,...
3252988,peter1023199,456780.0,Ducati - 90th anniversary,0.100000,Ducati - 90th anniversary,"['Simulation', 'Racing', 'Sports']",2016,456780.0
3252989,76561198071808318,444770.0,Mimpi dreams,0.766667,Mimpi dreams,"['Indie', 'Adventure', 'Cute', 'Puzzle-Platfor...",2016,444770.0
3252990,76561198107283457,354280.0,Chaostower,2.733333,Chaostower,"['Indie', 'Casual', 'Action', 'Simulation']",2016,354280.0
3252991,inven,433920.0,Aveyond 4: shadow of the mist,0.000000,Aveyond 4: shadow of the mist,"['RPG', 'Indie', 'Adventure', 'RPGMaker']",2016,433920.0
3252992,danebuchanan,485270.0,Arachnophobia,0.116667,Arachnophobia,"['Casual', 'Simulation', 'Psychological Horror...",2016,485270.0

In [51]:
Funciones1 = Funciones1.drop(columns=['item_id', 'item_name'], axis=1)

In [52]:
Funciones1['playtime_forever'] = Funciones1['playtime_forever'].astype(int)

In [53]:
Funciones1

,user_id,playtime_forever,app_name,genres,año,id
0,76561197970982479,0,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
1,js41637,0,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
2,Riot-Punch,0,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
3,doctr,1,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
4,corrupted_soul,1,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
...,...,...,...,...,...,...
3252988,peter1023199,0,Ducati - 90th anniversary,"['Simulation', 'Racing', 'Sports']",2016,456780.0
3252989,76561198071808318,0,Mimpi dreams,"['Indie', 'Adventure', 'Cute', 'Puzzle-Platfor...",2016,444770.0
3252990,76561198107283457,2,Chaostower,"['Indie', 'Casual', 'Action', 'Simulation']",2016,354280.0
3252991,inven,0,Aveyond 4: shadow of the mist,"['RPG', 'Indie', 'Adventure', 'RPGMaker']",2016,433920.0
3252992,danebuchanan,0,Arachnophobia,"['Casual', 'Simulation', 'Psychological Horror...",2016,485270.0

In [104]:
Funciones1.groupby(['user_id', 'año']).sum().reset_index()

,user_id,año,playtime_forever,app_name,genres,id
0,--000--,2006,15,Garry's mod,"['Sandbox', 'Multiplayer', 'Funny', 'Moddable'...",4000.0
1,--000--,2009,88,Killing floorLeft 4 dead 2Saints row 2,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",11280.0
2,--000--,2010,0,Super crate box,"['Free to Play', 'Indie', 'Platformer', 'Actio...",212800.0
3,--000--,2011,97,TerrariaSaints row: the thirdApb reloaded,"['Sandbox', 'Adventure', 'Survival', '2D', 'Mu...",274230.0
4,--000--,2012,1787,Counter-strike: global offensiveHero academySa...,"['FPS', 'Multiplayer', 'Shooter', 'Action', 'T...",1181050.0
...,...,...,...,...,...,...
715802,zzzmidmiss,2011,51,Mafia iiTotal war: shogun 2Saints row: the thi...,"['Action', 'Open World', 'Crime', 'Story Rich'...",817490.0
715803,zzzmidmiss,2012,84,Borderlands 2Hotline miamiThomas was aloneLitt...,"['FPS', 'Co-op', 'Action', 'RPG', 'Loot', 'Sho...",2105800.0
715804,zzzmidmiss,2013,1,Orion: preludeWarframeProteusRift,"['Dinosaurs', 'Action', 'FPS', 'Multiplayer', ...",594110.0
715805,zzzmidmiss,2014,0,Free to play,"['Free to Play', 'Documentary', 'e-sports']",245550.0
715806,zzzmidmiss,2016,0,Godus wars,"['Early Access', 'Strategy', 'Simulation', 'Go...",422420.0

In [54]:
Funciones1.to_csv('./Data/Data-Funciones/Funciones1.csv',index=False)

In [55]:
with gzip.open('./Data/Data-Funciones/Funciones1.csv.gz', 'wb') as f:
    Funciones1.to_csv(f, index=False, encoding='utf-8')

Def PlayTimeGenre( genero : str ): Debe devolver año con mas horas jugadas para dicho género.
Ejemplo de retorno: {"Año de lanzamiento con más horas jugadas para Género X" : 2013}

In [56]:
def PlayTimeGenre(genero):
    # Acceder al DataFrame global
    global Funciones1
    
    
    # Se filtra el DataFrame para el género específico
    df_genero = Funciones1[Funciones1['genres'].str.contains(genero, case=False, na=False)]

    # Se agrupa por año y calcula las horas jugadas
    horas_por_año = df_genero.groupby('año')['playtime_forever'].sum()

    # Se encuentra el año con más horas jugadas
    año_max_horas = horas_por_año.idxmax()

    # Se crea el diccionario de retorno
    resultado = {"Año de lanzamiento con más horas jugadas para {}: {}".format(genero, año_max_horas)}

    return resultado

In [57]:
PlayTimeGenre('Action')

{'Año de lanzamiento con más horas jugadas para Action: 2012'}

Def UserForGenre( genero : str ): Debe devolver el usuario que acumula más horas jugadas para el género dado y una lista de la acumulación de horas jugadas por año.
Ejemplo de retorno: {"Usuario con más horas jugadas para Género X" : us213ndjss09sdf, "Horas jugadas":[{Año: 2013, Horas: 203}, {Año: 2012, Horas: 100}, {Año: 2011, Horas: 23}]}

In [108]:
def UserForGenre(genero):
    global Funciones1 #leer csv, sacar el global 

    df_genero= Funciones1.groupby(['user_id', 'año']).sum().reset_index()

    df_genero = df_genero[df_genero['genres'].str.contains(genero)]

    # Encontrar al usuario con la máxima cantidad de playtime
    usuario_max_playtime = df_genero.loc[df_genero['playtime_forever'].idxmax()]['user_id']

    # Filtrar el DataFrame original por usuario y género
   # df_usuario_genero = Funciones1[(Funciones1['genres'].str.contains(genero)) & (Funciones1['user_id'] == usuario_max_playtime)]
    df_usuario_genero = Funciones1[(Funciones1['user_id'] == usuario_max_playtime)]
    # Agrupar por año y sumar el tiempo de juego
    poranio = df_usuario_genero.groupby('año')['playtime_forever'].sum().to_dict()

    # Crear un diccionario con la información
    dicc = {
        'usuario': usuario_max_playtime,
        'años': poranio
    }

    return dicc

In [109]:
UserForGenre('Action')

{'usuario': 'REBAS_AS_F-T',
 'años': {1996: 0,
  1998: 0,
  1999: 3,
  2000: 0,
  2001: 0,
  2002: 0,
  2003: 31,
  2004: 150,
  2005: 54,
  2006: 28,
  2007: 30,
  2008: 61,
  2009: 564,
  2010: 905,
  2011: 2534,
  2012: 3119,
  2013: 5555,
  2014: 6466,
  2015: 16343,
  2016: 19910,
  2017: 748}}

In [97]:
Funciones1['playtime_forever'][Funciones1['user_id']=='REBAS_AS_F-T'].sum()

56501

In [98]:
Funciones1['playtime_forever'][Funciones1['user_id']=='shinomegami'].sum()

44311

In [62]:
reviews = pd.read_csv('./Data/Data-Limpia/user_reviews_limpio.csv')

In [63]:
Funciones2 = pd.merge(reviews, steam, left_on='item_id', right_on='id', how='inner')

In [64]:
Funciones2

,user_id,item_id,recommend,sentiment_analysis,app_name,genres,año,id
0,76561197970982479,1250.0,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
1,death-hunter,1250.0,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
2,DJKamBer,1250.0,True,0,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
3,diego9031,1250.0,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
4,76561198081962345,1250.0,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
...,...,...,...,...,...,...,...,...
53834,llDracuwulf,307130.0,True,1,Asteria,"['Indie', 'Adventure', 'Action', 'Platformer',...",2014,307130.0
53835,ChrisCoroner,209120.0,True,2,Street fighter x tekken,"['Fighting', 'Action', 'Arcade', '2D Fighter',...",2012,209120.0
53836,MeloncraftLP,220090.0,True,1,The journey down: chapter one,"['Adventure', 'Point & Click', 'Indie', 'Comed...",2013,220090.0
53837,MeloncraftLP,262850.0,True,1,The journey down: chapter two,"['Adventure', 'Indie', 'Point & Click', 'Great...",2014,262850.0
53838,vinquility,431510.0,True,2,Mystic destinies: serendipity of aeons,"['Visual Novel', 'Otome', 'Female Protagonist'...",2016,431510.0

In [65]:
Funciones2 = Funciones2.drop(columns='item_id', axis=1)

In [66]:
Funciones2

,user_id,recommend,sentiment_analysis,app_name,genres,año,id
0,76561197970982479,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
1,death-hunter,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
2,DJKamBer,True,0,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
3,diego9031,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
4,76561198081962345,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
...,...,...,...,...,...,...,...
53834,llDracuwulf,True,1,Asteria,"['Indie', 'Adventure', 'Action', 'Platformer',...",2014,307130.0
53835,ChrisCoroner,True,2,Street fighter x tekken,"['Fighting', 'Action', 'Arcade', '2D Fighter',...",2012,209120.0
53836,MeloncraftLP,True,1,The journey down: chapter one,"['Adventure', 'Point & Click', 'Indie', 'Comed...",2013,220090.0
53837,MeloncraftLP,True,1,The journey down: chapter two,"['Adventure', 'Indie', 'Point & Click', 'Great...",2014,262850.0
53838,vinquility,True,2,Mystic destinies: serendipity of aeons,"['Visual Novel', 'Otome', 'Female Protagonist'...",2016,431510.0

In [68]:
Funciones2.to_csv('./Data/Data-Funciones/Funciones2.csv',index=False)

In [70]:
with gzip.open('./Data/Data-Funciones/Funciones2.csv.gz', 'wb') as f:
    Funciones2.to_csv(f, index=False, encoding='utf-8')

def UsersRecommend( año : int ): Devuelve el top 3 de juegos MÁS recomendados por usuarios para el año dado. (reviews.recommend = True y comentarios positivos/neutrales)
Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [71]:
def UsersRecommend(año):
    global Funciones2
    # Filtrar el DataFrame para el año y las recomendaciones positivas (True) y los sentimientos 1 y 2
    df_filtrado = Funciones2[(Funciones2['año'] == año) & (Funciones2['recommend'] == True) & (Funciones2['sentiment_analysis'].isin([1, 2]))]

    # Contar la frecuencia de cada juego
    juegos_frecuencia = df_filtrado['app_name'].value_counts().reset_index() #Ver user id (carga diferente)

    # Renombrar las columnas
    juegos_frecuencia.columns = ['app_name', 'count']

    # Seleccionar los tres juegos más recomendados
    top3_juegos = juegos_frecuencia.head(3)

    # Crear la lista de diccionarios para el resultado
    resultado = [{"Puesto {}: {}".format(i + 1, juego): count} for i, (juego, count) in enumerate(top3_juegos.values)]

    return resultado

In [84]:
UsersRecommend(2012)

[{'Puesto 1: Counter-strike: global offensive': 3265},
 {'Puesto 2: Borderlands 2': 524},
 {'Puesto 3: Planetside 2': 313}]

def UsersNotRecommend( año : int ): Devuelve el top 3 de juegos MENOS recomendados por usuarios para el año dado. (reviews.recommend = False y comentarios negativos)
Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [92]:
def UsersNotRecommend(año):
    global Funciones2
    # Filtrar el DataFrame para el año y las recomendaciones positivas (True) y los sentimientos 1 y 2
    df_filtrado = Funciones2[(Funciones2['año'] == año) & (Funciones2['recommend'] == False) & (Funciones2['sentiment_analysis']==0)]

    # Contar la frecuencia de cada juego
    juegos_frecuencia = df_filtrado['app_name'].value_counts().reset_index() #Ver user id (carga diferente)

    # Renombrar las columnas
    juegos_frecuencia.columns = ['app_name', 'count']

    # Seleccionar los tres juegos más recomendados
    top3_juegos = juegos_frecuencia.head(3)

    # Crear la lista de diccionarios para el resultado
    resultado = [{"Puesto {}: {}".format(i + 1, juego): count} for i, (juego, count) in enumerate(top3_juegos.values)]

    return resultado

In [95]:
UsersNotRecommend(2017)

[{'Puesto 1: Unturned': 27},
 {'Puesto 2: Robocraft': 21},
 {'Puesto 3: Ark: survival evolved': 13}]

def sentiment_analysis( año : int ): Según el año de lanzamiento, se devuelve una lista con la cantidad de registros de reseñas de usuarios que se encuentren categorizados con un análisis de sentimiento.
Ejemplo de retorno: {Negative = 182, Neutral = 120, Positive = 278}

In [ ]:
def sentiment_analysis(año):
    global Funciones2
    # Filtrar el DataFrame para el año dado
    df_filtrado = Funciones2[Funciones2['año'] == año]

    # Contar la cantidad de registros para cada análisis de sentimiento
    conteo_sentimientos = df_filtrado['sentiment_analysis'].value_counts().to_dict()

    # Crear la lista de diccionarios para el resultado
    resultado = {
        'Negative': conteo_sentimientos.get(0, 0),
        'Neutral': conteo_sentimientos.get(1, 0),
        'Positive': conteo_sentimientos.get(2, 0)
        }

    return resultado

In [ ]:
sentiment_analysis(2015)

{'Negative': 626, 'Neutral': 2824, 'Positive': 3025}

Si es un sistema de recomendación item-item:

def recomendacion_juego( id de producto ): Ingresando el id de producto, deberíamos recibir una lista con 5 juegos recomendados similares al ingresado.

Si es un sistema de recomendación user-item:

def recomendacion_usuario( id de usuario ): Ingresando el id de un usuario, deberíamos recibir una lista con 5 juegos recomendados para dicho usuario.