In [3]:
import pandas as pd
import numpy as np
import gzip
import json

In [4]:
steam = pd.read_csv('./Data\Data-Limpia\steam_games_limpio.csv')

In [5]:
steam

,app_name,genres,año,id
0,Lost summoner kitty,"['Strategy', 'Action', 'Indie', 'Casual', 'Sim...",2018,761140.0
1,Ironbound,"['Free to Play', 'Strategy', 'Indie', 'RPG', '...",2018,643980.0
2,Real pool 3d - poolians,"['Free to Play', 'Simulation', 'Sports', 'Casu...",2017,670290.0
3,弹炸人2222,"['Action', 'Adventure', 'Casual']",2017,767400.0
4,Log challenge,"['Action', 'Indie', 'Casual', 'Sports']",2016,773570.0
...,...,...,...,...
31326,Colony on mars,"['Strategy', 'Indie', 'Casual', 'Simulation']",2018,773640.0
31327,Logistical: south africa,"['Strategy', 'Indie', 'Casual']",2018,733530.0
31328,Russian roads,"['Indie', 'Simulation', 'Racing']",2018,610660.0
31329,Exit 2 - directions,"['Indie', 'Casual', 'Puzzle', 'Singleplayer', ...",2017,658870.0
31330,Maze run vr,"['Early Access', 'Adventure', 'Indie', 'Action...",2016,681550.0

In [6]:
items = pd.read_csv('./Data/Data-Limpia/user_items_limpio.csv')

In [7]:
items

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10.0,Counter-strike,0.100000
1,76561197970982479,20.0,Team fortress classic,0.000000
2,76561197970982479,30.0,Day of defeat,0.116667
3,76561197970982479,40.0,Deathmatch classic,0.000000
4,76561197970982479,50.0,Half-life: opposing force,0.000000
...,...,...,...,...
5094077,76561198329548331,346330.0,Brainbread 2,0.000000
5094078,76561198329548331,373330.0,All is dust,0.000000
5094079,76561198329548331,388490.0,One way to die: steam edition,0.050000
5094080,76561198329548331,521570.0,You have 10 seconds 2,0.066667
5094081,76561198329548331,519140.0,Minds eyes,0.050000

In [8]:
Funciones1 = pd.merge(items, steam, left_on='item_name', right_on='app_name', how='inner')

In [9]:
Funciones1

,user_id,item_id,item_name,playtime_forever,app_name,genres,año,id
0,76561197970982479,10.0,Counter-strike,0.100000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
1,js41637,10.0,Counter-strike,0.000000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
2,Riot-Punch,10.0,Counter-strike,0.000000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
3,doctr,10.0,Counter-strike,1.550000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
4,corrupted_soul,10.0,Counter-strike,1.800000,Counter-strike,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,10.0
...,...,...,...,...,...,...,...,...
3252988,peter1023199,456780.0,Ducati - 90th anniversary,0.100000,Ducati - 90th anniversary,"['Simulation', 'Racing', 'Sports']",2016,456780.0
3252989,76561198071808318,444770.0,Mimpi dreams,0.766667,Mimpi dreams,"['Indie', 'Adventure', 'Cute', 'Puzzle-Platfor...",2016,444770.0
3252990,76561198107283457,354280.0,Chaostower,2.733333,Chaostower,"['Indie', 'Casual', 'Action', 'Simulation']",2016,354280.0
3252991,inven,433920.0,Aveyond 4: shadow of the mist,0.000000,Aveyond 4: shadow of the mist,"['RPG', 'Indie', 'Adventure', 'RPGMaker']",2016,433920.0
3252992,danebuchanan,485270.0,Arachnophobia,0.116667,Arachnophobia,"['Casual', 'Simulation', 'Psychological Horror...",2016,485270.0

In [10]:
Funciones1 = Funciones1.drop(columns=['item_id', 'item_name', 'user_id', 'app_name', 'id'], axis=1)

In [11]:
Funciones1['playtime_forever'] = Funciones1['playtime_forever'].astype(int)

In [12]:
Funciones1

,playtime_forever,genres,año
0,0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000
1,0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000
2,0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000
3,1,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000
4,1,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000
...,...,...,...
3252988,0,"['Simulation', 'Racing', 'Sports']",2016
3252989,0,"['Indie', 'Adventure', 'Cute', 'Puzzle-Platfor...",2016
3252990,2,"['Indie', 'Casual', 'Action', 'Simulation']",2016
3252991,0,"['RPG', 'Indie', 'Adventure', 'RPGMaker']",2016
3252992,0,"['Casual', 'Simulation', 'Psychological Horror...",2016

In [14]:
#Funciones1.to_csv('./Data/Data-Funciones/Funciones1.csv',index=False)

In [13]:
with gzip.open('./Data/Data-Funciones/Funciones1.csv.gz', 'wb') as f:
    Funciones1.to_csv(f, index=False, encoding='utf-8')

Def PlayTimeGenre( genero : str ): Debe devolver año con mas horas jugadas para dicho género.
Ejemplo de retorno: {"Año de lanzamiento con más horas jugadas para Género X" : 2013}

In [14]:
def PlayTimeGenre(genero):
    df = pd.read_csv('./Data/Data-Funciones/Funciones1.csv.gz', compression='gzip')
    
    # Se filtra el DataFrame para el género específico
    df_genero = df[df['genres'].str.contains(genero, case=False, na=False)]

    # Se agrupa por año y calcula las horas jugadas
    horas_por_año = df_genero.groupby('año')['playtime_forever'].sum()

    # Se encuentra el año con más horas jugadas
    año_max_horas = horas_por_año.idxmax()

    # Se crea el diccionario de retorno
    resultado = {"Año de lanzamiento con más horas jugadas para {}: {}".format(genero, año_max_horas)}

    return resultado

In [15]:
PlayTimeGenre('Action')

{'Año de lanzamiento con más horas jugadas para Action: 2012'}

Def UserForGenre( genero : str ): Debe devolver el usuario que acumula más horas jugadas para el género dado y una lista de la acumulación de horas jugadas por año.
Ejemplo de retorno: {"Usuario con más horas jugadas para Género X" : us213ndjss09sdf, "Horas jugadas":[{Año: 2013, Horas: 203}, {Año: 2012, Horas: 100}, {Año: 2011, Horas: 23}]}

In [174]:
steam1 = pd.read_csv('./Data\Data-Limpia\steam_games_limpio.csv')

items1 = pd.read_csv('./Data/Data-Limpia/user_items_limpio.csv')

steam1 = steam1[['genres','id','año']]
items1 = items[['user_id','item_id','playtime_forever']]

In [175]:
steam1 = steam1.groupby('id').first().reset_index()

steam1 = steam1[steam1['año']!=0]

F_user_genre = steam1.merge(items, left_on='id', right_on='item_id', how='inner')

In [176]:
F_user_genre

,id,genres,año,user_id,item_id,item_name,playtime_forever
0,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,76561197970982479,10.0,Counter-strike,0.100000
1,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,js41637,10.0,Counter-strike,0.000000
2,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,Riot-Punch,10.0,Counter-strike,0.000000
3,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,doctr,10.0,Counter-strike,1.550000
4,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,corrupted_soul,10.0,Counter-strike,1.800000
...,...,...,...,...,...,...,...
4229121,528660.0,"['Indie', 'Casual', 'Action', 'Puzzle']",2016,SirexPower,528660.0,Spin rush,3.033333
4229122,528660.0,"['Indie', 'Casual', 'Action', 'Puzzle']",2016,thugnificent,528660.0,Spin rush,0.000000
4229123,529820.0,"['Action', 'Indie', 'VR']",2016,robinwalker,529820.0,Beyond power vr,0.000000
4229124,530720.0,"['Casual', 'Indie']",2016,CSMisBeast,530720.0,Solitaire royale,0.000000
4229125,530720.0,"['Casual', 'Indie']",2016,mayshowganmore,530720.0,Solitaire royale,0.000000

In [177]:
F_user_genre['playtime_forever'] = F_user_genre['playtime_forever'].astype(int)

In [178]:
with gzip.open('./Data/Data-Funciones/F_user_genre.csv.gz', 'wb') as f:
    Funciones1.to_csv(f, index=False, encoding='utf-8')

In [179]:
F_user_genre

,id,genres,año,user_id,item_id,item_name,playtime_forever
0,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,76561197970982479,10.0,Counter-strike,0
1,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,js41637,10.0,Counter-strike,0
2,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,Riot-Punch,10.0,Counter-strike,0
3,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,doctr,10.0,Counter-strike,1
4,10.0,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",2000,corrupted_soul,10.0,Counter-strike,1
...,...,...,...,...,...,...,...
4229121,528660.0,"['Indie', 'Casual', 'Action', 'Puzzle']",2016,SirexPower,528660.0,Spin rush,3
4229122,528660.0,"['Indie', 'Casual', 'Action', 'Puzzle']",2016,thugnificent,528660.0,Spin rush,0
4229123,529820.0,"['Action', 'Indie', 'VR']",2016,robinwalker,529820.0,Beyond power vr,0
4229124,530720.0,"['Casual', 'Indie']",2016,CSMisBeast,530720.0,Solitaire royale,0
4229125,530720.0,"['Casual', 'Indie']",2016,mayshowganmore,530720.0,Solitaire royale,0

In [180]:
def UserForGenre(genero):
    df = pd.read_csv('./Data/Data-Funciones/F_user_genre.csv.gz', compression='gzip')

    df_genero= df.groupby(['user_id', 'año']).sum().reset_index()

    df_genero = df_genero[df_genero['genres'].str.contains(genero)]

    # Encontrar al usuario con la máxima cantidad de playtime
    usuario_max_playtime = df_genero.loc[df_genero['playtime_forever'].idxmax()]['user_id']

    # Filtrar el DataFrame original por usuario y género
   # df_usuario_genero = Funciones1[(Funciones1['genres'].str.contains(genero)) & (Funciones1['user_id'] == usuario_max_playtime)]
    df_usuario_genero = df[(df['user_id'] == usuario_max_playtime)]
    # Agrupar por año y sumar el tiempo de juego
    poranio = df_usuario_genero.groupby('año')['playtime_forever'].sum().to_dict()

    # Crear un diccionario con la información
    dicc = {
        'usuario': usuario_max_playtime,
        'años': poranio
    }

    return dicc

In [181]:
UserForGenre('Action')

KeyError: 'user_id'

In [20]:
Funciones1['playtime_forever'][Funciones1['user_id']=='REBAS_AS_F-T'].sum()

56501

In [16]:
reviews = pd.read_csv('./Data/Data-Limpia/user_reviews_limpio.csv')

In [17]:
Funciones2 = pd.merge(reviews, steam, left_on='item_id', right_on='id', how='inner')

In [18]:
Funciones2

,user_id,item_id,recommend,sentiment_analysis,app_name,genres,año,id
0,76561197970982479,1250.0,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
1,death-hunter,1250.0,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
2,DJKamBer,1250.0,True,0,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
3,diego9031,1250.0,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
4,76561198081962345,1250.0,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009,1250.0
...,...,...,...,...,...,...,...,...
53046,llDracuwulf,307130.0,True,1,Asteria,"['Indie', 'Adventure', 'Action', 'Platformer',...",2014,307130.0
53047,ChrisCoroner,209120.0,True,2,Street fighter x tekken,"['Fighting', 'Action', 'Arcade', '2D Fighter',...",2012,209120.0
53048,MeloncraftLP,220090.0,True,1,The journey down: chapter one,"['Adventure', 'Point & Click', 'Indie', 'Comed...",2013,220090.0
53049,MeloncraftLP,262850.0,True,1,The journey down: chapter two,"['Adventure', 'Indie', 'Point & Click', 'Great...",2014,262850.0
53050,vinquility,431510.0,True,2,Mystic destinies: serendipity of aeons,"['Visual Novel', 'Otome', 'Female Protagonist'...",2016,431510.0

In [19]:
Funciones2 = Funciones2.drop(columns=['item_id', 'id'], axis=1)

In [20]:
Funciones2

,user_id,recommend,sentiment_analysis,app_name,genres,año
0,76561197970982479,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009
1,death-hunter,True,2,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009
2,DJKamBer,True,0,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009
3,diego9031,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009
4,76561198081962345,True,1,Killing floor,"['FPS', 'Zombies', 'Co-op', 'Survival', 'Actio...",2009
...,...,...,...,...,...,...
53046,llDracuwulf,True,1,Asteria,"['Indie', 'Adventure', 'Action', 'Platformer',...",2014
53047,ChrisCoroner,True,2,Street fighter x tekken,"['Fighting', 'Action', 'Arcade', '2D Fighter',...",2012
53048,MeloncraftLP,True,1,The journey down: chapter one,"['Adventure', 'Point & Click', 'Indie', 'Comed...",2013
53049,MeloncraftLP,True,1,The journey down: chapter two,"['Adventure', 'Indie', 'Point & Click', 'Great...",2014
53050,vinquility,True,2,Mystic destinies: serendipity of aeons,"['Visual Novel', 'Otome', 'Female Protagonist'...",2016

In [21]:
with gzip.open('./Data/Data-Funciones/Funciones2.csv.gz', 'wb') as f:
    Funciones2.to_csv(f, index=False, encoding='utf-8')

def UsersRecommend( año : int ): Devuelve el top 3 de juegos MÁS recomendados por usuarios para el año dado. (reviews.recommend = True y comentarios positivos/neutrales)
Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [31]:
def UsersRecommend(año):
    df = pd.read_csv('./Data/Data-Funciones/Funciones2.csv.gz', compression='gzip')    

    df_filtrado = df[(df['año'] == año) & (df['recommend'] == True) & (df['sentiment_analysis'].isin([1, 2]))]
    df_grouped = df_filtrado.groupby(['user_id', 'app_name']).size().reset_index(name='counts')
    juegos_frecuencia = df_grouped['app_name'].value_counts().reset_index() 
    df_top3 = juegos_frecuencia.head(3)
    resultado = [{"Puesto {}".format(i + 1): juego} for i, (juego, count) in enumerate(df_top3.values)]
    #resultado = [{"Puesto {}".format(i + 1): row['app_name']} for i, row in df_filtrado.iterrows()]
    return resultado

In [32]:
UsersRecommend(2010)

[{'Puesto 1': "Sid meier's civilization® v"},
 {'Puesto 2': 'Mount & blade: warband'},
 {'Puesto 3': 'Fallout: new vegas'}]

In [220]:
df_filtrado = Funciones2[(Funciones2['año'] == 2010) & (Funciones2['recommend'] == True) & (Funciones2['sentiment_analysis'].isin([1, 2]))]
df_grouped = df_filtrado.groupby(['user_id', 'app_name']).size().reset_index(name='counts')
juegos_frecuencia = df_grouped['app_name'].value_counts().reset_index() 
df_top3 = juegos_frecuencia.head(3)
resultado = {f"Puesto {i + 1}": str(juego) for i, (juego, count) in enumerate(df_top3.values)}
resultado

{'Puesto 1': "Sid meier's civilization® v",
 'Puesto 2': 'Mount & blade: warband',
 'Puesto 3': 'Fallout: new vegas'}

In [29]:
def UsersRecommend1(año):
    df = pd.read_csv('./Data/Data-Funciones/Funciones2.csv.gz', compression='gzip')    

    df_filtrado = df['app_name'][(df['año'] == año) & (df['recommend'] == True) & (df['sentiment_analysis'].isin([1, 2]))].value_counts().reset_index().head(3)
    resultado = [{"Puesto {}".format(i + 1): row['app_name']} for i, row in df_filtrado.iterrows()]
    return resultado

In [30]:
UsersRecommend1(2010)

[{'Puesto 1': "Sid meier's civilization® v"},
 {'Puesto 2': 'Mount & blade: warband'},
 {'Puesto 3': 'Fallout: new vegas'}]

def UsersNotRecommend( año : int ): Devuelve el top 3 de juegos MENOS recomendados por usuarios para el año dado. (reviews.recommend = False y comentarios negativos)
Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [148]:
def UsersNotRecommend(año):
    df = pd.read_csv('./Data/Data-Funciones/Funciones2.csv.gz', compression='gzip')    

    df_filtrado = df[(df['año'] == año) & (df['recommend'] == False) & (df['sentiment_analysis']==0)]
    df_grouped = df_filtrado.groupby(['user_id', 'app_name']).size().reset_index(name='counts')
    juegos_frecuencia = df_grouped['app_name'].value_counts().reset_index() 
    df_top3 = juegos_frecuencia.head(3)
    resultado = [{"Puesto {}".format(i + 1): juego} for i, (juego, count) in enumerate(df_top3.values)]
    return resultado

In [149]:
UsersNotRecommend(2017)

[{'Puesto 1': 'Unturned'},
 {'Puesto 2': 'Robocraft'},
 {'Puesto 3': 'Ark: survival evolved'}]

def sentiment_analysis( año : int ): Según el año de lanzamiento, se devuelve una lista con la cantidad de registros de reseñas de usuarios que se encuentren categorizados con un análisis de sentimiento.
Ejemplo de retorno: {Negative = 182, Neutral = 120, Positive = 278}

In [170]:
def sentiment_analysis1(año: int):
    df = pd.read_csv('./Data/Data-Funciones/Funciones2.csv.gz', compression='gzip')
    # Filtrar el DataFrame para el año dado
    df_filtrado = df[df['año'] == año]
    #Cuenta los comentarios positivos
    Positivos = df_filtrado[df_filtrado['sentiment_analysis']==2]['sentiment_analysis'].count()
    # Cuenta los comentarios negativos
    Negativos = df_filtrado[df_filtrado['sentiment_analysis']==0]['sentiment_analysis'].count()
    # Cuenta los comentarios neutrales
    Neutrales = df_filtrado[df_filtrado['sentiment_analysis']==1]['sentiment_analysis'].count()
    # Devolver conteos en un diccionario

    return {
        'Negative': str(int(Negativos)),
        'Positive': str(int(Positivos)),
        'Neutral':str(int(Neutrales))
    }

In [171]:
sentiment_analysis1(2014)

{'Negative': '625', 'Positive': '3128', 'Neutral': '2639'}

Si es un sistema de recomendación item-item:

def recomendacion_juego( id de producto ): Ingresando el id de producto, deberíamos recibir una lista con 5 juegos recomendados similares al ingresado.

Si es un sistema de recomendación user-item:

def recomendacion_usuario( id de usuario ): Ingresando el id de un usuario, deberíamos recibir una lista con 5 juegos recomendados para dicho usuario.